import {
    mdiAccount,
    mdiAccountBox,
    mdiAccountCheck,
    mdiAccountCircle,
    mdiAccountCog,
    mdiAccountGroup,
    mdiAccountRemove,
    mdiAccountVoice,
    mdiAlert,
    mdiAlertCircle,
    mdiApps,
    mdiArrowLeft,
    mdiArrowRight,
    mdiArrowUpBold,
    mdiBackupRestore,
    mdiBarcode,
    mdiBell,
    mdiBook,
    mdiBookCog,
    mdiBookMultiple,
    mdiBookMusic,
    mdiBookMusicOutline,
    mdiBookOpen,
    mdiBookOpenOutline,
    mdiBookOpenPageVariant,
    mdiBookOpenVariant,
    mdiBookRefreshOutline,
    mdiBookRemoveOutline,
    mdiBookSearchOutline,
    mdiBookSync,
    mdiBookshelf,
    mdiBroom,
    mdiBullhornVariant,
    mdiCellphone,
    mdiCheck,
    mdiCheckCircle,
    mdiCheckCircleOutline,
    mdiChevronDown,
    mdiChevronRight,
    mdiChevronUp,
    mdiCircleSmall,
    mdiClock,
    mdiClose,
    mdiCloseCircle,
    mdiCloudSearch,
    mdiCloudSync,
    mdiCloudUpload,
    mdiCodeTags,
    mdiCog,
    mdiCogOutline,
    mdiConnection,
    mdiConsole,
    mdiContentCopy,
    mdiCopyright,
    mdiDatabase,
    mdiDatabaseArrowRight,
    mdiDatabaseImport,
    mdiDelete,
    mdiDeleteAlert,
    mdiDeleteForever,
    mdiDeleteOutline,
    mdiDevices,
    mdiDomain,
    mdiDotsVertical,
    mdiDownload,
    mdiEarth,
    mdiEarthOff,
    mdiEmail,
    mdiEmailCheck,
    mdiExitToApp,
    mdiFaceMan,
    mdiFile,
    mdiFileCog,
    mdiFileDocument,
    mdiFileDocumentEditOutline,
    mdiFileDocumentRemoveOutline,
    mdiFileFind,
    mdiFileRefreshOutline,
    mdiFileSync,
    mdiFileUploadOutline,
    mdiFolder,
    mdiFolderOpenOutline,
    mdiFormatQuoteOpen,
    mdiGithub,
    mdiHelpCircleOutline,
    mdiHistory,
    mdiHome,
    mdiHomeGroup,
    mdiHuman,
    mdiHumanGreeting,
    mdiImage,
    mdiImport,
    mdiInformation,
    mdiKey,
    mdiLibraryShelves,
    mdiLink,
    mdiLock,
    mdiMagnify,
    mdiMenu,
    mdiMessageAlert,
    mdiOpenInNew,
    mdiPalette,
    mdiPaletteOutline,
    mdiPause,
    mdiPencil,
    mdiPlay,
    mdiPlayCircleOutline,
    mdiPlaylistMusic,
    mdiPlus,
    mdiProgressClock,
    mdiProgressWrench,
    mdiRefresh,
    mdiReload,
    mdiRss,
    mdiScriptTextOutline,
    mdiServer,
    mdiShieldAccount,
    mdiShieldCheck,
    mdiShieldEdit,
    mdiShuffle,
    mdiSkipNext,
    mdiSkipPrevious,
    mdiSourceBranch,
    mdiStarHalf,
    mdiSwapHorizontal,
    mdiSwapHorizontalBold,
    mdiTag,
    mdiTagHeart,
    mdiTagMultiple,
    mdiTextBoxOutline,
    mdiTranslate,
    mdiTrendingUp,
    mdiUpdate,
    mdiUpload,
    mdiVolumeHigh,
    mdiWaveform,
    mdiWeatherNight,
    mdiWeatherSunny,
    mdiWidgets,
} from '@mdi/js';
import { h, type Component, type FunctionalComponent } from 'vue';

/**
 * SVG paths used by application-owned `mdi-*` icon names.
 *
 * Keep this explicit so Vite can tree-shake the thousands of unused @mdi/js
 * exports. The accompanying test fails when application code introduces an
 * icon name that is missing here.
 */
export const localMdiPaths: Readonly<Record<string, string>> = {
    'mdi-account': mdiAccount,
    'mdi-account-box': mdiAccountBox,
    'mdi-account-check': mdiAccountCheck,
    'mdi-account-circle': mdiAccountCircle,
    'mdi-account-cog': mdiAccountCog,
    'mdi-account-group': mdiAccountGroup,
    'mdi-account-remove': mdiAccountRemove,
    'mdi-account-voice': mdiAccountVoice,
    'mdi-alert': mdiAlert,
    'mdi-alert-circle': mdiAlertCircle,
    'mdi-apps': mdiApps,
    'mdi-arrow-left': mdiArrowLeft,
    'mdi-arrow-right': mdiArrowRight,
    'mdi-arrow-up-bold': mdiArrowUpBold,
    'mdi-backup-restore': mdiBackupRestore,
    'mdi-barcode': mdiBarcode,
    'mdi-bell': mdiBell,
    'mdi-book': mdiBook,
    'mdi-book-cog': mdiBookCog,
    'mdi-book-multiple': mdiBookMultiple,
    'mdi-book-music': mdiBookMusic,
    'mdi-book-music-outline': mdiBookMusicOutline,
    'mdi-book-open': mdiBookOpen,
    'mdi-book-open-outline': mdiBookOpenOutline,
    'mdi-book-open-page-variant': mdiBookOpenPageVariant,
    'mdi-book-open-variant': mdiBookOpenVariant,
    'mdi-book-refresh-outline': mdiBookRefreshOutline,
    'mdi-book-remove-outline': mdiBookRemoveOutline,
    'mdi-book-search-outline': mdiBookSearchOutline,
    'mdi-book-sync': mdiBookSync,
    'mdi-bookshelf': mdiBookshelf,
    'mdi-broom': mdiBroom,
    'mdi-bullhorn-variant': mdiBullhornVariant,
    'mdi-cellphone': mdiCellphone,
    'mdi-check': mdiCheck,
    'mdi-check-circle': mdiCheckCircle,
    'mdi-check-circle-outline': mdiCheckCircleOutline,
    'mdi-chevron-down': mdiChevronDown,
    'mdi-chevron-right': mdiChevronRight,
    'mdi-chevron-up': mdiChevronUp,
    'mdi-circle-small': mdiCircleSmall,
    'mdi-clock': mdiClock,
    'mdi-close': mdiClose,
    'mdi-close-circle': mdiCloseCircle,
    'mdi-cloud-search': mdiCloudSearch,
    'mdi-cloud-sync': mdiCloudSync,
    'mdi-cloud-upload': mdiCloudUpload,
    'mdi-code-tags': mdiCodeTags,
    'mdi-cog': mdiCog,
    'mdi-cog-outline': mdiCogOutline,
    'mdi-connection': mdiConnection,
    'mdi-console': mdiConsole,
    'mdi-content-copy': mdiContentCopy,
    'mdi-copyright': mdiCopyright,
    'mdi-database': mdiDatabase,
    'mdi-database-arrow-right': mdiDatabaseArrowRight,
    'mdi-database-import': mdiDatabaseImport,
    'mdi-delete': mdiDelete,
    'mdi-delete-alert': mdiDeleteAlert,
    'mdi-delete-forever': mdiDeleteForever,
    'mdi-delete-outline': mdiDeleteOutline,
    'mdi-devices': mdiDevices,
    'mdi-domain': mdiDomain,
    'mdi-dots-vertical': mdiDotsVertical,
    'mdi-download': mdiDownload,
    'mdi-earth': mdiEarth,
    'mdi-earth-off': mdiEarthOff,
    'mdi-email': mdiEmail,
    'mdi-email-check': mdiEmailCheck,
    'mdi-exit-to-app': mdiExitToApp,
    'mdi-face-man': mdiFaceMan,
    'mdi-file': mdiFile,
    'mdi-file-cog': mdiFileCog,
    'mdi-file-document': mdiFileDocument,
    'mdi-file-document-edit-outline': mdiFileDocumentEditOutline,
    'mdi-file-document-remove-outline': mdiFileDocumentRemoveOutline,
    'mdi-file-find': mdiFileFind,
    'mdi-file-refresh-outline': mdiFileRefreshOutline,
    'mdi-file-sync': mdiFileSync,
    'mdi-file-upload-outline': mdiFileUploadOutline,
    'mdi-folder': mdiFolder,
    'mdi-folder-open-outline': mdiFolderOpenOutline,
    'mdi-format-quote-open': mdiFormatQuoteOpen,
    'mdi-github': mdiGithub,
    'mdi-history': mdiHistory,
    'mdi-home': mdiHome,
    'mdi-home-group': mdiHomeGroup,
    'mdi-human': mdiHuman,
    'mdi-human-greeting': mdiHumanGreeting,
    'mdi-image': mdiImage,
    'mdi-import': mdiImport,
    'mdi-information': mdiInformation,
    'mdi-key': mdiKey,
    'mdi-library-shelves': mdiLibraryShelves,
    'mdi-link': mdiLink,
    'mdi-lock': mdiLock,
    'mdi-magnify': mdiMagnify,
    'mdi-menu': mdiMenu,
    'mdi-message-alert': mdiMessageAlert,
    'mdi-open-in-new': mdiOpenInNew,
    'mdi-palette': mdiPalette,
    'mdi-palette-outline': mdiPaletteOutline,
    'mdi-pause': mdiPause,
    'mdi-pencil': mdiPencil,
    'mdi-play': mdiPlay,
    'mdi-play-circle-outline': mdiPlayCircleOutline,
    'mdi-playlist-music': mdiPlaylistMusic,
    'mdi-plus': mdiPlus,
    'mdi-progress-clock': mdiProgressClock,
    'mdi-progress-wrench': mdiProgressWrench,
    'mdi-refresh': mdiRefresh,
    'mdi-reload': mdiReload,
    'mdi-rss': mdiRss,
    'mdi-script-text-outline': mdiScriptTextOutline,
    'mdi-server': mdiServer,
    'mdi-shield-account': mdiShieldAccount,
    'mdi-shield-check': mdiShieldCheck,
    'mdi-shield-edit': mdiShieldEdit,
    'mdi-shuffle': mdiShuffle,
    'mdi-skip-next': mdiSkipNext,
    'mdi-skip-previous': mdiSkipPrevious,
    'mdi-source-branch': mdiSourceBranch,
    'mdi-star-half': mdiStarHalf,
    'mdi-swap-horizontal': mdiSwapHorizontal,
    'mdi-swap-horizontal-bold': mdiSwapHorizontalBold,
    'mdi-tag': mdiTag,
    'mdi-tag-heart': mdiTagHeart,
    'mdi-tag-multiple': mdiTagMultiple,
    'mdi-text-box-outline': mdiTextBoxOutline,
    'mdi-translate': mdiTranslate,
    'mdi-trending-up': mdiTrendingUp,
    'mdi-update': mdiUpdate,
    'mdi-upload': mdiUpload,
    'mdi-volume-high': mdiVolumeHigh,
    'mdi-waveform': mdiWaveform,
    'mdi-weather-night': mdiWeatherNight,
    'mdi-weather-sunny': mdiWeatherSunny,
    'mdi-widgets': mdiWidgets,
};

type LocalMdiIconProps = {
    tag: string | object;
    icon?: unknown;
    disabled?: boolean;
};

export const LocalMdiIcon: FunctionalComponent<LocalMdiIconProps> = (props, context) => {
    const name = typeof props.icon === 'string' ? props.icon : '';
    const path = localMdiPaths[name] || mdiHelpCircleOutline;

    if (import.meta.dev && !localMdiPaths[name]) {
        console.warn(`[Talebook] Unregistered local icon: ${name || '<empty>'}`);
    }

    return h(props.tag as Component, context.attrs, [
        h('svg', {
            class: 'v-icon__svg',
            xmlns: 'http://www.w3.org/2000/svg',
            viewBox: '0 0 24 24',
            role: 'img',
            'aria-hidden': 'true',
        }, [h('path', { d: path })]),
    ]);
};
