from .builtin_capabilities import BUILTIN_CAPABILITY_PROVIDERS, BuiltinCapabilityProvider
from .book_sources import BOOK_SOURCE_PROVIDERS
from .domains import (
    Annotation,
    BookFile,
    BookMetadata,
    Category,
    CheckReport,
    ItemFailure,
    Page,
    PushReceipt,
    Review,
    SourceBook,
    SourceBookDetail,
    SourceChapter,
    SourceContent,
    SourceState,
    ToolInput,
    ToolOutput,
    ToolReport,
)
from .enrichment import EXTERNAL_CONNECTOR_PROVIDERS
from .interfaces import (
    AnnotationProvider,
    CAPABILITY_INTERFACES,
    ExtraFeatureProvider,
    MetadataProvider,
    PluginContext,
    PushProvider,
    ReviewProvider,
    SourceProvider,
    TransformProvider,
    contract_violations,
)
from .mock import MockMultiTabProvider
from .push import PUSH_PROVIDERS, PUSH_PROVIDERS_BY_DEVICE, DevicePushProvider
from .protocol import (
    ACTIONS,
    CATEGORIES,
    PROTOCOL_VERSION,
    ManifestError,
    PluginManifest,
    UpstreamAuthError,
    UpstreamError,
    ProviderItem,
    UpstreamRateLimitError,
    ProviderResult,
)
from .weread import WEREAD_PLUGIN_KEY, WereadProvider, parse_weread_export
from .triggers import TRIGGER_AUTO, TRIGGER_MANUAL, TRIGGER_SCHEMA, trigger_of


# 内置插件清单。运行时只遍历这个元组，不认识其中任何一个具体插件。
ALL_BUILTIN_PROVIDERS = (
    MockMultiTabProvider(),
    WereadProvider(),
    *BUILTIN_CAPABILITY_PROVIDERS,
    *BOOK_SOURCE_PROVIDERS,
    *EXTERNAL_CONNECTOR_PROVIDERS,
    *PUSH_PROVIDERS,
)


__all__ = [
    "ACTIONS",
    "ALL_BUILTIN_PROVIDERS",
    "CATEGORIES",
    "PROTOCOL_VERSION",
    "ManifestError",
    "MockMultiTabProvider",
    "BuiltinCapabilityProvider",
    "BUILTIN_CAPABILITY_PROVIDERS",
    "BOOK_SOURCE_PROVIDERS",
    "Annotation",
    "AnnotationProvider",
    "BookFile",
    "BookMetadata",
    "CAPABILITY_INTERFACES",
    "Category",
    "CheckReport",
    "DevicePushProvider",
    "PUSH_PROVIDERS",
    "PUSH_PROVIDERS_BY_DEVICE",
    "EXTERNAL_CONNECTOR_PROVIDERS",
    "ExtraFeatureProvider",
    "ItemFailure",
    "MetadataProvider",
    "Page",
    "PluginContext",
    "PluginManifest",
    "PushProvider",
    "PushReceipt",
    "UpstreamAuthError",
    "UpstreamError",
    "ProviderItem",
    "UpstreamRateLimitError",
    "ProviderResult",
    "Review",
    "ReviewProvider",
    "SourceBook",
    "SourceBookDetail",
    "SourceChapter",
    "SourceContent",
    "SourceState",
    "SourceProvider",
    "TRIGGER_AUTO",
    "TRIGGER_MANUAL",
    "TRIGGER_SCHEMA",
    "ToolInput",
    "ToolOutput",
    "ToolReport",
    "TransformProvider",
    "WEREAD_PLUGIN_KEY",
    "WereadProvider",
    "contract_violations",
    "parse_weread_export",
    "trigger_of",
]
