"""插件平台的公共能力、领域对象与协议。

具体插件及其注册清单位于 ``webserver.plugins`` 的类型目录和
``webserver.plugins.register``，不得从本模块导出。
"""

from .domains import (
    Annotation,
    BookFile,
    BookMetadata,
    Category,
    CheckReport,
    ItemFailure,
    Page,
    PushReceipt,
    Review,
    SourceBook,
    SourceBookDetail,
    SourceChapter,
    SourceContent,
    SourceState,
    ToolInput,
    ToolOutput,
    ToolReport,
)
from .interfaces import (
    AnnotationProvider,
    CAPABILITY_INTERFACES,
    ExtraFeatureProvider,
    MetadataProvider,
    PluginContext,
    PushProvider,
    ReviewProvider,
    SourceProvider,
    TransformProvider,
    contract_violations,
)
from .protocol import (
    ACTIONS,
    CATEGORIES,
    PROTOCOL_VERSION,
    ManifestError,
    PluginManifest,
    ProviderItem,
    ProviderResult,
    UpstreamAuthError,
    UpstreamError,
    UpstreamRateLimitError,
)
from .triggers import TRIGGER_AUTO, TRIGGER_MANUAL, TRIGGER_SCHEMA, trigger_of


__all__ = [
    "ACTIONS",
    "Annotation",
    "AnnotationProvider",
    "BookFile",
    "BookMetadata",
    "CAPABILITY_INTERFACES",
    "CATEGORIES",
    "Category",
    "CheckReport",
    "ExtraFeatureProvider",
    "ItemFailure",
    "ManifestError",
    "MetadataProvider",
    "PROTOCOL_VERSION",
    "Page",
    "PluginContext",
    "PluginManifest",
    "ProviderItem",
    "ProviderResult",
    "PushProvider",
    "PushReceipt",
    "Review",
    "ReviewProvider",
    "SourceBook",
    "SourceBookDetail",
    "SourceChapter",
    "SourceContent",
    "SourceProvider",
    "SourceState",
    "TRIGGER_AUTO",
    "TRIGGER_MANUAL",
    "TRIGGER_SCHEMA",
    "ToolInput",
    "ToolOutput",
    "ToolReport",
    "TransformProvider",
    "UpstreamAuthError",
    "UpstreamError",
    "UpstreamRateLimitError",
    "contract_violations",
    "trigger_of",
]
