import { readFileSync } from 'node:fs';
import { test, expect } from '@playwright/test';

test.skip(!process.env.TALEBOOK_UPGRADE_URL || !process.env.TALEBOOK_UPGRADE_CREDENTIALS, 'Requires a disposable real Docker backend');

test('real backend login, library, reader, upgrade status and responsive layout', async ({ page }, testInfo) => {
    const expectedVersion = process.env.TALEBOOK_UPGRADE_EXPECTED_VERSION || 'v2';
    const credentials = JSON.parse(readFileSync(process.env.TALEBOOK_UPGRADE_CREDENTIALS!, 'utf8'));
    const login = await page.request.post('/api/user/sign_in', { form: credentials });
    expect((await login.json()).err).toBe('ok');
    await page.goto('/');
    await expect(page.locator('body')).not.toContainText('not_installed');
    const books = await page.request.get('/api/index');
    expect((await books.json()).new_books.length).toBeGreaterThan(0);
    await page.goto('/read/1');
    await expect(page.locator('body')).toBeVisible();
    await page.goto('/admin/settings/general');
    const title = page.getByRole('heading', { name: '应用升级', exact: true });
    await expect(title).toBeVisible({ timeout: 20000 });
    await title.scrollIntoViewIfNeeded();
    await expect(page.getByText(`当前应用：${expectedVersion}`, { exact: true })).toBeVisible();
    await page.screenshot({ path: testInfo.outputPath('upgrade-desktop.png'), fullPage: false });
    // A stale tab must refresh before a new backend can execute its operation.
    await page.evaluate(() => { document.documentElement.dataset.talebookVersion = 'old-tab'; });
    await page.getByRole('button', { name: '检查版本', exact: true }).click();
    await page.waitForFunction(expected => document.documentElement.dataset.talebookVersion === expected, expectedVersion);
    await expect(title).toBeVisible();
    await page.setViewportSize({ width: 320, height: 780 });
    await title.scrollIntoViewIfNeeded();
    await expect(title).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.screenshot({ path: testInfo.outputPath('upgrade-mobile.png'), fullPage: false });
    const install = page.getByRole('button', { name: '下载并安装', exact: true });
    if (await install.count()) {
        await install.focus();
        await page.keyboard.press('Enter');
        await expect(page.getByRole('dialog')).toBeVisible();
        await page.screenshot({ path: testInfo.outputPath('upgrade-confirm.png') });
        await expect.poll(() => page.getByRole('dialog').evaluate(dialog => dialog.contains(document.activeElement))).toBe(true);
    await page.keyboard.press('Escape');
        await expect(page.getByRole('dialog')).not.toBeVisible();
        await expect(install).toBeFocused();
    }
    await page.context().addCookies([{ name: 'theme', value: 'dark', url: process.env.TALEBOOK_UPGRADE_URL! }]);
    await page.emulateMedia({ colorScheme: 'dark', reducedMotion: 'reduce' });
    await page.reload();
    await expect(page.locator('.v-application')).toHaveClass(/v-theme--dark/);
    await title.scrollIntoViewIfNeeded();
    await page.screenshot({ path: testInfo.outputPath('upgrade-dark.png'), fullPage: false });
});

test('local version management, confirmation, validation and keyboard focus', async ({ page }, testInfo) => {
    test.skip(process.env.TALEBOOK_UPGRADE_EXPECTED_VERSION !== 'v4', 'Requires signed v2/v3/v4 management fixture');
    const credentials = JSON.parse(readFileSync(process.env.TALEBOOK_UPGRADE_CREDENTIALS!, 'utf8'));
    expect((await (await page.request.post('/api/user/sign_in', { form: credentials })).json()).err).toBe('ok');
    await page.goto('/admin/settings/general');
    const library = page.getByRole('region', { name: '本地应用版本' });
    const historyTrigger = page.getByRole('button', { name: '管理历史版本', exact: true });
    const history = page.getByRole('dialog', { name: '管理历史版本', exact: true });
    const detail = page.locator('[role="dialog"][aria-labelledby="upgrade-management-title"]');
    await expect(historyTrigger).toBeVisible({ timeout: 20000 });
    await expect(library).not.toBeVisible();
    await historyTrigger.scrollIntoViewIfNeeded();
    await page.screenshot({ path: testInfo.outputPath('upgrade-compact.png') });
    await historyTrigger.focus();
    await page.keyboard.press('Enter');
    await expect(library).toBeVisible();
    const keep = page.getByRole('button', { name: '保留 3 个版本 / 设置清理' });
    await keep.focus();
    await page.keyboard.press('Enter');
    await expect(detail).toBeVisible();
    await expect.poll(() => detail.evaluate(dialog => dialog.contains(document.activeElement))).toBe(true);
    await page.keyboard.press('Escape');
    await expect(keep).toBeFocused();
    await expect(history).toBeVisible();
    await keep.click();
    const input = detail.getByRole('spinbutton', { name: '保留数量' });
    await input.fill('21');
    await page.getByRole('button', { name: '保存并清理', exact: true }).click();
    await expect(input).toBeFocused();
    await input.fill('3');
    await page.getByRole('button', { name: '保存并清理', exact: true }).click();
    await expect(detail).not.toBeVisible();
    await expect(history.getByText('保留数量已保存，清理已完成。', { exact: true })).toBeVisible();
    const activate = page.getByRole('button', { name: '使用此版本：v2', exact: true });
    await activate.click();
    await expect(detail).toContainText('数据库');
    await expect.poll(() => detail.evaluate(dialog => dialog.contains(document.activeElement))).toBe(true);
    await page.keyboard.press('Escape');
    await expect(activate).toBeFocused();
    const remove = page.getByRole('button', { name: '删除版本 v2', exact: true });
    await remove.click();
    await expect(detail).toContainText('删除后将无法直接切换到此版本');
    await expect.poll(() => detail.evaluate(dialog => dialog.contains(document.activeElement))).toBe(true);
    await page.keyboard.press('Escape');
    await expect(remove).toBeFocused();
    await history.locator('.v-card-text').first().evaluate(el => { el.scrollTop = 0; });
    await page.screenshot({ path: testInfo.outputPath('versions-desktop.png') });
    await page.setViewportSize({ width: 320, height: 780 });
    await history.locator('.v-card-text').first().evaluate(el => { el.scrollTop = 0; });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    expect(await history.locator('.v-card-text').first().evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
    await page.screenshot({ path: testInfo.outputPath('versions-mobile.png') });
    await keep.click();
    await expect(detail.getByRole('spinbutton', { name: '保留数量' })).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: testInfo.outputPath('retention-mobile.png') });
    await expect.poll(() => detail.evaluate(dialog => dialog.contains(document.activeElement))).toBe(true);
    await page.keyboard.press('Escape');
    await history.getByRole('button', { name: '关闭', exact: true }).click();
    await expect(history).not.toBeVisible();
    await expect(historyTrigger).toBeFocused();
    await historyTrigger.click();
    await expect.poll(() => history.evaluate(dialog => dialog.contains(document.activeElement))).toBe(true);
    await page.keyboard.press('Escape');
    await expect(history).not.toBeVisible();
    await expect(historyTrigger).toBeFocused();
    await page.context().addCookies([{ name: 'theme', value: 'dark', url: process.env.TALEBOOK_UPGRADE_URL! }]);
    await page.emulateMedia({ colorScheme: 'dark', reducedMotion: 'reduce' });
    await page.reload();
    await expect(page.locator('.v-application')).toHaveClass(/v-theme--dark/);
    await historyTrigger.click();
    await expect(history).toBeVisible();
    await history.locator('.v-card-text').first().evaluate(el => { el.scrollTop = 0; });
    await page.screenshot({ path: testInfo.outputPath('versions-dark.png') });
});
